# Themes
include themes/mocha.conf

# Fonts
font_family FiraCode Nerd Font Reg
font_size 11

# Keyboard move focus
map alt+h neighboring_window left
map alt+l neighboring_window right
map alt+k neighboring_window up
map alt+j neighboring_window down

map alt+left  neighboring_window left
map alt+right neighboring_window right
map alt+up    neighboring_window up
map alt+down  neighboring_window down

# Urls
detect_urls yes

# Border windows
window_margin_width 12

# tab
tab_bar_style   powerline 
close_on_child_death yes
disable_ligatures never
map kitty_mod+t new_tab_with_cwd
map kitty_mod+n new_window_with_cwd

# Clipboard
map ctrl+c copy_to_clipboard
map ctrl+v paste_from_clipboard

# shell
shell zsh

# configure tap
map ctrl+shift+f1 set_tab_title
map ctrl+shift+i set_tab_title 
map ctrl+shift+k set_tab_title 
map ctrl+shift+o set_tab_title 
