term xterm-256color

# Font Configuration
font_size 11.0
font_family      JetBrainsMono Nerd Font Mono

# Window Configuration
window_padding_width 12
background_opacity 1.0
background_blur 32
hide_window_decorations yes

# Cursor Configuration
cursor_shape block
cursor_blink_interval 1

# change to x11 or wayland or leave auto
linux_display_server auto

# Scrollback
scrollback_lines 3000
wheel_scroll_min_lines 1

# Terminal features
copy_on_select yes
strip_trailing_spaces smart

# Key bindings for common actions
map alt+left  neighboring_window left
map alt+right neighboring_window right
map alt+up    neighboring_window up
map alt+down  neighboring_window down

map alt+h   neighboring_window left
map alt+l   neighboring_window right
map alt+k   neighboring_window up
map alt+j   neighboring_window down

map ctrl+plus change_font_size all +1.0
map ctrl+minus change_font_size all -1.0
map ctrl+0 change_font_size all 0

# Create new tabs and windows in current directory
map kitty_mod+t new_tab_with_cwd
map kitty_mod+n new_window_with_cwd

# Tab configuration
tab_bar_style powerline
tab_bar_align left

# Shell integration
shell_integration enabled

# configure tap
map ctrl+shift+f1 set_tab_title 󰇥
map ctrl+shift+f2 set_tab_title 
map ctrl+shift+f3 set_tab_title 
map ctrl+shift+f3 set_tab_title 󱘯
map ctrl+shift+f4 set_tab_title 
map ctrl+shift+f5 set_tab_title 
map ctrl+shift+f6 set_tab_title 
map ctrl+shift+f9 set_tab_title

# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #

# you can choose themes from $HOME/.config/kitty/kitty-themes/
include ./kitty-themes/dank-theme.conf
include dank-tabs.conf
