"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
console_title_template = "{{ .Folder }}"
version = 4

[[blocks]]
alignment = "left"
newline = true
type = "prompt"

[[blocks.segments]]
foreground = "#ffbebc"
leading_diamond = "<#ff70a6>  </>"
style = "diamond"
template = "{{ .UserName }} <#ffffff>on</>"
type = "session"

[[blocks.segments]]
foreground = "#bc93ff"
style = "diamond"
template = " {{ .CurrentDate | date .Format }} "
type = "time"

[blocks.segments.options]
time_format = "Monday <#ffffff>at</> 3:04 PM"

[[blocks.segments]]
foreground = "#ee79d1"
style = "diamond"
template = " {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} "
type = "git"

[blocks.segments.options]
branch_icon = " "
fetch_status = true
fetch_upstream_icon = true

[[blocks]]
alignment = "right"
type = "prompt"

[[blocks.segments]]
foreground = "#a9ffb4"
style = "plain"
type = "text"

[[blocks.segments]]
foreground = "#a9ffb4"
style = "diamond"
template = " {{ .FormattedMs }}s <#ffffff></>"
type = "executiontime"

[blocks.segments.options]
style = "dallas"
threshold = 0

[[blocks.segments]]
style = "diamond"
template = "  "
type = "root"

[blocks.segments.options]
root_icon = " "

[[blocks.segments]]
foreground = "#94ffa2"
style = "diamond"
template = " <#ffffff>MEM:</> {{ round .PhysicalPercentUsed .Precision }}% ({{ (div ((sub .PhysicalTotalMemory .PhysicalAvailableMemory)|float64) 1073741824.0) }}/{{ (div .PhysicalTotalMemory 1073741824.0) }}GB)"
type = "sysinfo"

[[blocks]]
alignment = "left"
newline = true
type = "prompt"

[[blocks.segments]]
foreground = "#ffafd2"
leading_diamond = "<#00c7fc>  </><#ffafd2>{</>"
style = "diamond"
template = "  {{ .Path }} "
trailing_diamond = "<#ffafd2>}</>"
type = "path"

[blocks.segments.options]
folder_icon = ""
folder_separator_icon = "  "
home_icon = "home"
style = "agnoster_full"

[[blocks.segments]]
foreground = "#A9FFB4"
foreground_templates = ["{{ if gt .Code 0 }}#ef5350{{ end }}"]
style = "plain"
template = "  "
type = "status"

[blocks.segments.options]
always_enabled = true

[transient_prompt]
background = "transparent"
foreground = "#FEF5ED"
template = " "
